/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.NumberEditor;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ComprarIngresso extends javax.swing.JFrame {
  
    Cinema cinema;
    private Venda venda;   
           
    public ComprarIngresso() {
        venda = new Venda();
        construtor();
    }  
        
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        FinalizarjButton = new javax.swing.JButton();
        CancelarjButton = new javax.swing.JButton();
        tipoIngressojLabel = new javax.swing.JLabel();
        inteirajRadioButton = new javax.swing.JRadioButton();
        quantidadejLabel = new javax.swing.JLabel();
        meiajRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSessaojTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        contVendajButton = new javax.swing.JButton();
        quantidadejSpinner = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastrojMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        cadastroSessaojMenuItem = new javax.swing.JMenuItem();
        cadastroFilmejMenuItem = new javax.swing.JMenuItem();
        dadosjMenu = new javax.swing.JMenu();
        dadosSessaojMenuItem = new javax.swing.JMenuItem();
        dadosFilmejMenuItem = new javax.swing.JMenuItem();
        sairjMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingressos");
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        FinalizarjButton.setBackground(new java.awt.Color(255, 255, 255));
        FinalizarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/imprimeIng-icon.jpg"))); // NOI18N
        FinalizarjButton.setText("Finalizar venda");
        FinalizarjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalizarjButtonMouseClicked(evt);
            }
        });

        CancelarjButton.setBackground(new java.awt.Color(255, 255, 255));
        CancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/cancel_icon.png"))); // NOI18N
        CancelarjButton.setText("Cancelar");
        CancelarjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarjButtonMouseClicked(evt);
            }
        });

        tipoIngressojLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipoIngressojLabel.setText("Tipo de ingresso:");

        inteirajRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(inteirajRadioButton);
        inteirajRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        inteirajRadioButton.setText("Inteira");

        quantidadejLabel.setForeground(new java.awt.Color(255, 255, 255));
        quantidadejLabel.setText("Quantidade:");

        meiajRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(meiajRadioButton);
        meiajRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        meiajRadioButton.setText("Meia");
        meiajRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meiajRadioButtonActionPerformed(evt);
            }
        });

        ListaSessaojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                " Filme", "Sala", "Horário", "Data", "Dub/Leg", "3D", "Dia Semana", "Valor Ingresso", "Lotação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaSessaojTable.setGridColor(new java.awt.Color(0, 0, 0));
        ListaSessaojTable.setSelectionBackground(new java.awt.Color(255, 51, 102));
        ListaSessaojTable.setSelectionForeground(new java.awt.Color(240, 240, 240));
        ListaSessaojTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaSessaojTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSessaojTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaSessaojTable);
        if (ListaSessaojTable.getColumnModel().getColumnCount() > 0) {
            ListaSessaojTable.getColumnModel().getColumn(0).setPreferredWidth(120);
            ListaSessaojTable.getColumnModel().getColumn(1).setPreferredWidth(55);
            ListaSessaojTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            ListaSessaojTable.getColumnModel().getColumn(3).setPreferredWidth(65);
            ListaSessaojTable.getColumnModel().getColumn(4).setPreferredWidth(55);
            ListaSessaojTable.getColumnModel().getColumn(5).setPreferredWidth(10);
            ListaSessaojTable.getColumnModel().getColumn(6).setPreferredWidth(62);
            ListaSessaojTable.getColumnModel().getColumn(7).setPreferredWidth(63);
            ListaSessaojTable.getColumnModel().getColumn(8).setPreferredWidth(35);
        }

        contVendajButton.setBackground(new java.awt.Color(255, 255, 255));
        contVendajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/ingresso_icon.png"))); // NOI18N
        contVendajButton.setText("Continuar venda");
        contVendajButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contVendajButtonMouseClicked(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        cadastrojMenu.setBackground(new java.awt.Color(0, 0, 0));
        cadastrojMenu.setForeground(new java.awt.Color(255, 255, 255));
        cadastrojMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/cadastro_icon2.jpg"))); // NOI18N
        cadastrojMenu.setText("Cadastro");

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Cadastrar");

        cadastroSessaojMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        cadastroSessaojMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/sessao_icon.png"))); // NOI18N
        cadastroSessaojMenuItem.setText("Sessão");
        cadastroSessaojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroSessaojMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroSessaojMenuItem);

        cadastroFilmejMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        cadastroFilmejMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/icon_filme.png"))); // NOI18N
        cadastroFilmejMenuItem.setText("Filme");
        cadastroFilmejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroFilmejMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroFilmejMenuItem);

        cadastrojMenu.add(jMenu1);

        dadosjMenu.setBackground(new java.awt.Color(255, 255, 255));
        dadosjMenu.setText("Dados cadastrados");

        dadosSessaojMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        dadosSessaojMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/sessao_icon.png"))); // NOI18N
        dadosSessaojMenuItem.setText("Sessões");
        dadosSessaojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosSessaojMenuItemActionPerformed(evt);
            }
        });
        dadosjMenu.add(dadosSessaojMenuItem);

        dadosFilmejMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        dadosFilmejMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/icon_filme.png"))); // NOI18N
        dadosFilmejMenuItem.setText("Filmes");
        dadosFilmejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosFilmejMenuItemActionPerformed(evt);
            }
        });
        dadosjMenu.add(dadosFilmejMenuItem);

        cadastrojMenu.add(dadosjMenu);

        jMenuBar1.add(cadastrojMenu);

        sairjMenu.setBorder(null);
        sairjMenu.setForeground(new java.awt.Color(255, 255, 255));
        sairjMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/icon_sair.png"))); // NOI18N
        sairjMenu.setText("Sair");
        sairjMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairjMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(sairjMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantidadejLabel)
                    .addComponent(tipoIngressojLabel))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inteirajRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(meiajRadioButton))
                    .addComponent(quantidadejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(FinalizarjButton)
                .addGap(30, 30, 30)
                .addComponent(contVendajButton)
                .addGap(28, 28, 28)
                .addComponent(CancelarjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoIngressojLabel)
                    .addComponent(inteirajRadioButton)
                    .addComponent(meiajRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadejLabel)
                    .addComponent(quantidadejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinalizarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarjButton)
                    .addComponent(contVendajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
     
    private void FinalizarjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalizarjButtonMouseClicked
        if(cinema.ingressos.isEmpty() && ListaSessaojTable.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma sessão para a qual deseja vender o(s) ingresso(s).");
        }
        else if(cinema.ingressos.isEmpty() && (Integer)quantidadejSpinner.getValue() == 0){
                     JOptionPane.showMessageDialog(null, "Por favor, selecione a quantidade de ingressos que deseja vender.");
            }
            else{
                if(ListaSessaojTable.getSelectedRowCount() == 0){
                    for(int i=0; i<cinema.ingressos.size(); i++){
                       venda.calcPrecoTotal(cinema.ingressos.get(i).getPrecoIngresso());
                    }

                    new FormVenda(venda).setVisible(true);
                    this.dispose();
                }
                else{
                    vendeIngresso();            
                    for(int i=0; i<cinema.ingressos.size(); i++){
                       venda.calcPrecoTotal(cinema.ingressos.get(i).getPrecoIngresso());
                    }

                    new FormVenda(venda).setVisible(true);
                    this.dispose();
                }
            }    
    }//GEN-LAST:event_FinalizarjButtonMouseClicked

    private void CancelarjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarjButtonMouseClicked
        if(cinema.ingressos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não há venda para cancelar.");
        }
        else if(JOptionPane.showConfirmDialog(null, "Deseja cancelar a venda?","Cancelar venda", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            for(int i=0; i<cinema.ingressos.size(); i++){
               cinema.sessoes.get(cinema.ingressos.get(i).getPosicao())
                      .calcLotaçao(cinema.sessoes.get(cinema.ingressos.get(i).getPosicao()).getNomeSala(), 
                                   cinema.sessoes.get(cinema.ingressos.get(i).getPosicao()).getLotaçao(),
                                   false);
            }

            cinema.ingressos.clear();
            atualizaTabela();
        }
    }//GEN-LAST:event_CancelarjButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      //atualizaTabela();
    }//GEN-LAST:event_formWindowOpened

    private void meiajRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meiajRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meiajRadioButtonActionPerformed

    private void contVendajButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contVendajButtonMouseClicked
        if(ListaSessaojTable.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma sessão para a qual deseja vender o(s) ingresso(s).");
        }
        else if((Integer)quantidadejSpinner.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Por favor, selecione a quantidade de ingressos que deseja vender.");
        }
            else{            
                vendeIngresso();
                atualizaTabela();
                atualizaCampos();
            }    
    }//GEN-LAST:event_contVendajButtonMouseClicked

    private void ListaSessaojTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSessaojTableMouseClicked
         int posicao = ListaSessaojTable.getSelectedRow();
         atualizaSpinner(cinema.sessoes.get(posicao).getLotaçao());
    
    }//GEN-LAST:event_ListaSessaojTableMouseClicked

    private void sairjMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairjMenuMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Deseja fechar a aplicação?","Sair", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_sairjMenuMouseClicked

    private void dadosSessaojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosSessaojMenuItemActionPerformed
        if(!cinema.sessoes.isEmpty()){
            new ListaSessao(false).setVisible(true);
            this.dispose();
        }
         else{
            JOptionPane.showMessageDialog(null, "Não há sessões cadastradas.");
         }
    }//GEN-LAST:event_dadosSessaojMenuItemActionPerformed

    private void dadosFilmejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosFilmejMenuItemActionPerformed
        if(!cinema.sessoes.isEmpty()){
            new ListaFilme(false).setVisible(true);
            this.dispose();
        }
         else{
            JOptionPane.showMessageDialog(null, "Não há filmes cadastrados.");
         }
    }//GEN-LAST:event_dadosFilmejMenuItemActionPerformed

    private void cadastroFilmejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroFilmejMenuItemActionPerformed
        new FormFilme().setVisible(true);  
        this.dispose();
            
    }//GEN-LAST:event_cadastroFilmejMenuItemActionPerformed

    private void cadastroSessaojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroSessaojMenuItemActionPerformed
       new FormSessao().setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_cadastroSessaojMenuItemActionPerformed
    
    public void atualizaTabela(){
        DecimalFormat df = new DecimalFormat("0.00");  
        DefaultTableModel modelo = (DefaultTableModel) ListaSessaojTable.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<cinema.sessoes.size(); i++){
            String tresD;
            if(cinema.sessoes.get(i).getTresD() == true){
                tresD = "Sim";
            } 
            else{
                tresD = "Não";
            }
            
            modelo.addRow(new Object[]{
                         cinema.sessoes.get(i).getNomeFilme(),
                         cinema.sessoes.get(i).getNomeSala(),
                         cinema.sessoes.get(i).getHorario(),
                         cinema.sessoes.get(i).getData(),
                         cinema.sessoes.get(i).getDubladoLegendado(),
                         tresD,
                         cinema.sessoes.get(i).getDiaSemana(),
                         df.format(cinema.sessoes.get(i).getValorIngresso()),
                         cinema.sessoes.get(i).getLotaçao()
            });
            
        }
    }
      
    
    public void atualizaSpinner(int maximo){
      SpinnerNumberModel model = new SpinnerNumberModel(0, 0, maximo, 1); 
      quantidadejSpinner.setModel(model);
      
      NumberEditor numbereditor = (NumberEditor)quantidadejSpinner.getEditor();
      numbereditor.getTextField().setEditable(false);
       
    }
    
    public void atualizaCampos(){
        inteirajRadioButton.setSelected(true);
        quantidadejSpinner.setValue(0);
    }
    
    public void geraFilmes(){
        for(int i=0; i<5; i++){
            Filme filme = new Filme();
            filme.setTitulo("Filme"+i);
            filme.setGenero("Genero"+i);
            filme.setDuraçao("16:00");
            filme.setClassIndicativa("Livre");
            
            cinema.filmes.add(filme);
        }
    }
    
    public void geraSessao(){
        for(int i=0; i<5; i++){
            Sessão sessao = new Sessão();
            sessao.setNomeFilme(cinema.filmes.get(i).getTitulo());
            sessao.setTresD(true);
            sessao.setHorario("21:00");
            sessao.setData("02/06/2019");
            sessao.setDubladoLegendado("Legendado");
            sessao.setNomeSala("Sala Vip 02");
            sessao.setDiaSemana("Sábado");
            sessao.calcValorIngresso(true, "Vip", "Sábado");
            sessao.calcLotaçao("Sala Vip 02");
            
            cinema.sessoes.add(sessao);
        }
    }
    
    @SuppressWarnings("static-access")
    public void vendeIngresso(){
        int posicao = ListaSessaojTable.getSelectedRow();
        String tipoIngresso;
        if(inteirajRadioButton.isSelected()){
            tipoIngresso = inteirajRadioButton.getText();
        }
        else{
            tipoIngresso = meiajRadioButton.getText();
        }
        
        for(int i=0; i<(Integer) quantidadejSpinner.getValue(); i++){
            Ingresso ingresso = new Ingresso();
            ingresso.setTipo(tipoIngresso);
            ingresso.calcPrecoIngresso(cinema.sessoes.get(posicao).getValorIngresso());
            ingresso.setDadosSessao(cinema.sessoes.get(posicao).getNomeFilme(), cinema.sessoes.get(posicao).getNomeSala(),
            cinema.sessoes.get(posicao).getData(), cinema.sessoes.get(posicao).getHorario(), cinema.sessoes.get(posicao).getTresD(), posicao);
            cinema.ingressos.add(ingresso);
            cinema.sessoes.get(posicao).calcLotaçao(cinema.sessoes.get(posicao).getNomeSala(), cinema.sessoes.get(posicao).getLotaçao(), true);
             
        }
    }
    
    public void construtor(){
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.BLACK);
        headerRenderer.setForeground(Color.WHITE);
        for (int i = 0; i < ListaSessaojTable.getModel().getColumnCount(); i++) {
            ListaSessaojTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        
        if(cinema.filmes.isEmpty())
            geraFilmes();
        if(cinema.sessoes.isEmpty())
            geraSessao();
        
        atualizaCampos();
        atualizaTabela();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarIngresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarjButton;
    private javax.swing.JButton FinalizarjButton;
    private javax.swing.JTable ListaSessaojTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem cadastroFilmejMenuItem;
    private javax.swing.JMenuItem cadastroSessaojMenuItem;
    private javax.swing.JMenu cadastrojMenu;
    private javax.swing.JButton contVendajButton;
    private javax.swing.JMenuItem dadosFilmejMenuItem;
    private javax.swing.JMenuItem dadosSessaojMenuItem;
    private javax.swing.JMenu dadosjMenu;
    private javax.swing.JRadioButton inteirajRadioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton meiajRadioButton;
    private javax.swing.JLabel quantidadejLabel;
    private javax.swing.JSpinner quantidadejSpinner;
    private javax.swing.JMenu sairjMenu;
    private javax.swing.JLabel tipoIngressojLabel;
    // End of variables declaration//GEN-END:variables
}
