/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author PedroH
 */
public class EditFilme extends javax.swing.JFrame {
    
    Cinema cinema;
    private int pos;
    private boolean nav;
    
    public EditFilme() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
    }
    
    public EditFilme(int posicao, boolean nav){
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        this.nav = nav;
        pos = posicao;
        atualizaCampos(posicao);
    }
           
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        cadastroButton = new javax.swing.JButton();
        listaFilmesButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        tituloTextField = new javax.swing.JTextField();
        generoLabel = new javax.swing.JLabel();
        generoTextField = new javax.swing.JTextField();
        duracaoLabel = new javax.swing.JLabel();
        duracaoTextField = new javax.swing.JTextField();
        classIndLabel = new javax.swing.JLabel();
        classIndComboBox = new javax.swing.JComboBox<>();
        salvarAltjButton = new javax.swing.JButton();
        voltarButton1 = new javax.swing.JButton();
        tituloLabel2 = new javax.swing.JLabel();
        tituloTextField1 = new javax.swing.JTextField();
        generoLabel2 = new javax.swing.JLabel();
        generoTextField1 = new javax.swing.JTextField();
        duracaoLabel2 = new javax.swing.JLabel();
        duracaoTextField1 = new javax.swing.JTextField();
        classIndLabel2 = new javax.swing.JLabel();
        classIndComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame1formWindowOpened(evt);
            }
        });

        cadastroButton.setText("Cadastrar");
        cadastroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroButtonMouseClicked(evt);
            }
        });
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });

        listaFilmesButton.setText("Filmes cadastrados");
        listaFilmesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFilmesButtonMouseClicked(evt);
            }
        });

        voltarButton.setText("Voltar");

        tituloLabel.setText("Título");

        generoLabel.setText("Gênero");

        duracaoLabel.setText("Duração");

        classIndLabel.setText("Classificação Indicativa");

        classIndComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma opção>", "Livre", "10 anos", "12 anos", "14 anos", "16 anos", "18 anos" }));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(classIndLabel)
                        .addGap(26, 26, 26)
                        .addComponent(classIndComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(cadastroButton)
                        .addGap(18, 18, 18)
                        .addComponent(listaFilmesButton)
                        .addGap(18, 18, 18)
                        .addComponent(voltarButton))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(duracaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(duracaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tituloLabel))
                    .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(generoLabel))
                    .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(duracaoLabel))
                    .addComponent(duracaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(classIndLabel))
                    .addComponent(classIndComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroButton)
                    .addComponent(listaFilmesButton)
                    .addComponent(voltarButton))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filme - Alterar dados");

        salvarAltjButton.setBackground(new java.awt.Color(255, 255, 255));
        salvarAltjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/icon_save.png"))); // NOI18N
        salvarAltjButton.setText("Salvar alterações");
        salvarAltjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarAltjButtonMouseClicked(evt);
            }
        });

        voltarButton1.setBackground(new java.awt.Color(255, 255, 255));
        voltarButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/cancel_icon.png"))); // NOI18N
        voltarButton1.setText("Cancelar");
        voltarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarButton1MouseClicked(evt);
            }
        });

        tituloLabel2.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel2.setText("Título:");

        generoLabel2.setForeground(new java.awt.Color(255, 255, 255));
        generoLabel2.setText("Gênero:");

        duracaoLabel2.setForeground(new java.awt.Color(255, 255, 255));
        duracaoLabel2.setText("Duração:");

        try{
            javax.swing.text.MaskFormatter horario= new javax.swing.text.MaskFormatter("##:##");
            duracaoTextField1 = new javax.swing.JFormattedTextField(horario);

        }
        catch (Exception e){

        }

        classIndLabel2.setForeground(new java.awt.Color(255, 255, 255));
        classIndLabel2.setText("Classificação Indicativa:");

        classIndComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10 anos", "12 anos", "14 anos", "16 anos", "18 anos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(classIndLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(classIndComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tituloLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(generoLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(duracaoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duracaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(generoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tituloTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(salvarAltjButton)
                        .addGap(33, 33, 33)
                        .addComponent(voltarButton1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLabel2)
                    .addComponent(tituloTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoLabel2)
                    .addComponent(generoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracaoLabel2)
                    .addComponent(duracaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classIndLabel2)
                    .addComponent(classIndComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarAltjButton)
                    .addComponent(voltarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroButtonMouseClicked
        
        
        
        

    }//GEN-LAST:event_cadastroButtonMouseClicked

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroButtonActionPerformed

    private void listaFilmesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFilmesButtonMouseClicked
        
    }//GEN-LAST:event_listaFilmesButtonMouseClicked

    private void jFrame1formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1formWindowOpened

    }//GEN-LAST:event_jFrame1formWindowOpened

    private void salvarAltjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarAltjButtonMouseClicked
        Filme filme = new Filme();
        filme.setTitulo(tituloTextField1.getText());
        filme.setGenero(generoTextField1.getText());
        filme.setDuraçao(duracaoTextField1.getText());
        filme.setClassIndicativa(classIndComboBox1.getSelectedItem().toString());

        cinema.filmes.set(pos, filme);
        JOptionPane.showMessageDialog(null, "Filme cadastrado com sucesso.");
        new ListaFilme(nav).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_salvarAltjButtonMouseClicked

    private void voltarButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarButton1MouseClicked
        new ListaFilme(nav).setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_voltarButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFilme().setVisible(true);
            }
        });
    }
    
    public void atualizaCampos(int posicao){
        tituloTextField1.setText(cinema.filmes.get(posicao).getTitulo());
        generoTextField1.setText(cinema.filmes.get(posicao).getGenero()); 
        duracaoTextField1.setText(cinema.filmes.get(posicao).getDuraçao());
        classIndComboBox1.setSelectedItem(cinema.filmes.get(posicao).getClassIndicativa()); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroButton;
    private javax.swing.JComboBox<String> classIndComboBox;
    private javax.swing.JComboBox<String> classIndComboBox1;
    private javax.swing.JLabel classIndLabel;
    private javax.swing.JLabel classIndLabel2;
    private javax.swing.JLabel duracaoLabel;
    private javax.swing.JLabel duracaoLabel2;
    private javax.swing.JTextField duracaoTextField;
    private javax.swing.JTextField duracaoTextField1;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JLabel generoLabel2;
    private javax.swing.JTextField generoTextField;
    private javax.swing.JTextField generoTextField1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton listaFilmesButton;
    private javax.swing.JButton salvarAltjButton;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel tituloLabel2;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JTextField tituloTextField1;
    private javax.swing.JButton voltarButton;
    private javax.swing.JButton voltarButton1;
    // End of variables declaration//GEN-END:variables
}
